version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: order_app_db
    restart: always
    environment:
      POSTGRES_USER: order_app
      POSTGRES_PASSWORD: order_app_pass
      POSTGRES_DB: order_app_db
    ports:
      - '5433:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pg_data:

networks:
  app-network:
    driver: bridge
